name: "roe"
fqdn: "192.168.0.12"
appOfAppsName: "science-platform"
vaultUrl: "http://192.168.0.12"
vaultPathPrefix: "secret/kvv2"

applications:
  mobu: true
  nublado: true
  portal: true
  postgres: true
  squareone: true
  tap: true
