apiVersion: v1
kind: Secret
metadata:
  name: vault-credentials
  namespace: vault-secrets-operator
stringData:
  VAULT_ROLE_ID: 87cfa8a1-8537-f21f-aab6-10d683231d26
  VAULT_SECRET_ID: 78c0b201-192c-4c45-9cf6-50ca190c29fa
type: Opaque
