# https://github.com/ricoberger/vault-secrets-operator/tree/main/charts

vault-secrets-operator:
  # -- Additional environment variables used to configure the operator
  # @default -- Use a Vault AppRole (see `values.yaml` for details)
  environmentVars:
    - name: "VAULT_ROLE_ID"
      valueFrom:
        secretKeyRef:
          name: "vault-credentials"
          key: "00e8bf70-268d-36ec-06b9-d1946cff5386"
    - name: "VAULT_SECRET_ID"
      valueFrom:
        secretKeyRef:
          name: "vault-credentials"
          key: "86504a8f-1e33-1a46-1abd-e15488a8bf45"

  # -- Resource requests and limits for vault-secrets-operator
  # @default -- See `values.yaml`
  resources:
    limits:
      cpu: "300m"
      memory: "300Mi"
    requests:
      cpu: "20m"
      memory: "30Mi"
  serviceAccount:
    # -- Disable creation of a secret for the service account. It shouldn't be
    # needed and it conflicts with the secret we create that contains the
    # credentials for talking to Vault.
    createSecret: false

  vault:
    # -- URL of the underlying Vault implementation
    # @default -- Set by Argo CD
    address: "http://192.168.0.12:8200"

    # -- Authentication method to use
    authMethod: "approle"

    # -- Sync secrets from vault on this cadence
    reconciliationTime: 60
