apiVersion: v1
kind: Secret
metadata:
  name: vault-credentials
  namespace: vault-secrets-operator
stringData:
  VAULT_ROLE_ID: 00e8bf70-268d-36ec-06b9-d1946cff5386
  VAULT_SECRET_ID: 4d42ae68-cf36-bef7-a61a-48eae359c031
type: Opaque
