vault:
  global:
    tlsDisable: true
    namespace: default

  injector:
    enabled: false

  server:
    ingress:
      enabled: false

    dataStorage:
      enabled: false

    standalone:
      enabled: false

    ha:
      enabled: true
      replicas: 1

    resources:
      limits:
        cpu: "1"
        memory: "350Mi"
      requests:
        cpu: "50m"
        memory: "35Mi"
