ingress-nginx:
  controller:
    config:
      server-snippet: |
        set $auth_error_body '';
        set $auth_status '';
        set $auth_www_authenticate '';
        location @autherror {
          default_type application/json;
          if ($auth_status = 400) {
            add_header Cache-Control "no-cache, must-revalidate" always;
            add_header WWW-Authenticate $auth_www_authenticate always;
            return 400 $auth_error_body;
          }
          add_header Cache-Control "no-cache, must-revalidate" always;
          add_header WWW-Authenticate $auth_www_authenticate always;
          return 403;
        }

    metrics:
      enabled: true

    resources:
      limits:
        cpu: "4"
        memory: "5Gi"
      requests:
        cpu: "80m"
        memory: "500Mi"

    service:
      type: NodePort
      externalTrafficPolicy: Local

    podLabels:
      hub.jupyter.org/network-access-proxy-http: "true"

  admissionWebhooks:
    enabled: false

vaultCertificate:
  enabled: false

global:
  vaultSecretsPath: ""

