config:
  base-url: "https://gafaelfawr.local"

  authentication:
    type: "github"  # 어떤 타입이든 괜찮지만...
    fake:
      enabled: true  # 이 설정이 핵심! 자동 인증 처리

secrets:
  secretKey: "super-secret-session-key"

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: gafaelfawr.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - gafaelfawr.local
      secretName: gafaelfawr-tls

image:
  repository: lsstsqre/gafaelfawr
  tag: "7.1.0"
