exposurelog_password:
  description: "Password for the exposurelog database."
  if: exposurelog_db
  vault: kvv2/data/postgres#exposurelog_password

gafaelfawr_password:
  description: "Password for the Gafaelfawr database."
  if: gafaelfawr_db
  vault: kvv2/data/postgres#gafaelfawr_password

lovelog_password:
  description: "Password for the lovelog database."
  if: lovelog_db
  generate:
    type: password

narrativelog_password:
  description: "Password for the narrativelog database."
  if: narrativelog_db
  vault: kvv2/data/postgres#narrativelog_password

nublado3_password:
  description: "Password for the Nublado v3 JupyterHub session database."
  if: nublado3_db
  vault: kvv2/data/postgres#nublado3_password

root_password:
  description: "Administrator password for the whole PostgreSQL installation."
  vault: kvv2/data/postgres#root_password

timessquare_password:
  description: "Password for the times-square database."
  if: timessquare_db
  vault: kvv2/data/postgres#timessquare_password
