existingSecret:
  name: phalanx-postgres-secret   # Vault에서 가져온 Kubernetes Secret 이름
  items:
    - name: root_password         # PostgreSQL root 비밀번호
      key: root_password          # Kubernetes Secret 내의 key
    - name: gafaelfawr_password   # PostgreSQL Gafaelfawr DB 비밀번호
      key: gafaelfawr_password
    - name: exposurelog_password  # Exposurelog DB 비밀번호
      key: exposurelog_password
    - name: narrativelog_password # Narrativelog DB 비밀번호
      key: narrativelog_password
    - name: nublado3_password     # Nublado3 DB 비밀번호
      key: nublado3_password
    - name: timessquare_password  # Timesquare DB 비밀번호
      key: timessquare_password

#  PVC 관련 설정
postgresStorageClass: manual
volumeName: postgres-pv  # 선택 사항 (정확하게 PV 바인딩하고 싶다면)
