apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cm-service-pg
  labels:
    {{- include "cm-service.labels" . | nindent 4 }}
spec:
  instances: 1
  bootstrap:
    initdb:
      database: cm-service
      owner: cm-service
      secret:
        name: postgres-secret
  storage:
    size: 1Gi
