---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cm-service-output
  labels:
    {{- include "cm-service.labels" . | nindent 4 }}
spec:
  {{- with .Values.config.outputVolume.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.config.outputVolume.storage }}
{{- with .Values.worker.htcondor.fsRemoteDir }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cm-service-htcondor
  labels:
    {{- include "cm-service.labels" $ | nindent 4 }}
spec:
  {{- with .storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .storage }}
{{- end }}
