apiVersion: v1
kind: ConfigMap
metadata:
  name: "cm-service-config-worker"
  labels:
    {{- include "cm-service.labels" . | nindent 4 }}
data:
  {{- with .Values.worker.htcondor.config }}
  config: |
    {{- .contents | nindent 4 }}
  {{- end }}
  {{- with .Values.worker.htcondor.scheddAddress }}
  scheddAddress: |
    {{- .contents | nindent 4 }}
  {{- end }}
