redis:
  persistence:
    enabled: false

config:
  internalDatabase: false
  databaseUrl: "postgresql://gafaelfawr:azwell!@postgres.default.svc.cluster.local:5432/gafaelfawr"

  # 로그인 없이 고정 유저로 인증 (테스트 전용)
  authenticationBackend: "static"

  static:
    users:
      - username: "localadmin"
        uid: "1000"
        name: "Local Admin"
        email: "local@admin.com"
        groups:
          - "exec:admin"
          - "exec:portal"
          - "exec:notebook"
          - "read:image"
          - "read:tap"
          - "write:files"

  initialAdmins:
    - "localadmin"

  # 기본 로그인 리디렉션 허용
  loginRedirect: true

  # Gafaelfawr 자체 주소 (필요시 수정)
  baseUrl: "http://gafaelfawr.local"

  # 로컬에서 인증 없이 접근할 수 있는 기본 scope (옵션)
  anonymous:
    scopes: []

# TLS 사용 여부 (로컬 테스트 시엔 false로 해도 됨)
ingress:
  tls: false

# 필수 설정: 템플릿에서 사용하는 host 값
global:
  host: "gafaelfawr.local"
  baseUrl: "http://gafaelfawr.local"
