redis:
  persistence:
    enabled: false
  password: "azwell!"

config:
  internalDatabase: false
  databaseUrl: "postgresql://gafaelfawr:azwell%21@postgres.default.svc.cluster.local:5432/gafaelfawr"

  # authentication은 Secret으로 이전 필요 ❗

existingSecret:
  name: gafaelfawr
  keys:
    bootstrapToken: bootstrap-token
    sessionSecret: session-secret

authentication:
  type: static
  static:
    users:
      - username: "localadmin"
        uid: "1000"
        name: "Local Admin"
        email: "local@admin.com"
        groups:
          - "exec:admin"
          - "exec:portal"
          - "exec:notebook"
          - "read:image"
          - "read:tap"
          - "write:files"

ingress:
  tls: false

global:
  host: "gafaelfawr.local"
  baseUrl: "http://gafaelfawr.local"

