redis:
  persistence:
    enabled: false
  password: "azwell!"

config:
  internalDatabase: false
  databaseUrl: "postgresql://gafaelfawr:azwell%21@postgres.default.svc.cluster.local:5432/gafaelfawr"  # '!'는 %21로 인코딩
  sessionSecret: "supersecret123"
  bootstrapToken: "gt-azwell-bootstrap-token"

  authentication:
    type: static
    static:
      users:
        - username: "localadmin"
          uid: "1000"
          name: "Local Admin"
          email: "local@admin.com"
          groups:
            - "exec:admin"
            - "exec:portal"
            - "exec:notebook"
            - "read:image"
            - "read:tap"
            - "write:files"
      admins:
        - "localadmin"

  loginRedirect: true

ingress:
  tls: false

global:
  host: "gafaelfawr.local"
  baseUrl: "http://gafaelfawr.local"
