redis:
  persistence:
    enabled: false
  password: "azwell!"

config:
  internalDatabase: false
  databaseUrl: "postgresql://gafaelfawr:azwell%21@postgres.default.svc.cluster.local:5432/gafaelfawr"

  oidcServer:
    enabled: true

existingSecret:
  name: gafaelfawr
  keys:
    bootstrapToken: bootstrap-token
    sessionSecret: session-secret
    githubClientId: github-client-id
    githubClientSecret: github-client-secret

authentication:
  type: github
  github:
    clientId: null  # Secret에서 가져오므로 null로 설정
    clientSecret: null
    callbackUrl: "https://rsp.azwellsoft.com/login"
    allowedOrganizations:
      - azwellsoft

ingress:
  enabled: true
  tls: true
  additionalHosts: []
  tls:
    - hosts:
        - rsp.azwellsoft.com
      secretName: rsp-azwellsoft-com-tls

global:
  host: "rsp.azwellsoft.com"
  baseUrl: "https://rsp.azwellsoft.com"
